#!/usr/bin/env bash
# This script was generated by bashly 1.2.10 (https://bashly.dev)
# Modifying it manually is not recommended

# :wrapper.bash3_bouncer
if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
  printf "bash version 4 or higher is required\n" >&2
  exit 1
fi

# :command.master_script

# :command.version_command
version_command() {
  echo "$version"
}

# :command.usage
tm_usage() {
  printf "tm - Taskmage: Taskwarrior-inspired task management tool following the todo.txt specification\n\n"

  printf "%s\n" "Usage:"
  printf "  tm [COMMAND]\n"
  printf "  tm [COMMAND] --help | -h\n"
  printf "  tm --version | -v\n"
  echo
  # :command.usage_commands
  printf "%s\n" "Commands:"
  printf "  %s   Add a task\n" "add    "
  printf "  %s   List tasks (default)\n" "list   "
  printf "  %s   Mark a task as completed\n" "done   "
  printf "  %s   Delete a task - move to deleted file\n" "delete "
  printf "  %s   Purge a task - remove from deleted file\n" "purge  "
  printf "  %s   Archive completed tasks - move from todo file to done file\n" "archive"
  echo

  # :command.long_usage
  if [[ -n "$long_usage" ]]; then
    printf "%s\n" "Options:"

    # :command.usage_fixed_flags
    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo
    printf "  %s\n" "--version, -v"
    printf "    Show version number\n"
    echo

    # :command.usage_environment_variables
    printf "%s\n" "Environment Variables:"

    # :environment_variable.usage
    printf "  %s\n" "TASKMAGE_TODOFILE (required)"
    printf "    Path to todo file to be used by taskmage\n    (recommended: ~/Documents/todo/todo.txt)\n"
    echo

    # :environment_variable.usage
    printf "  %s\n" "TASKMAGE_DONEFILE (required)"
    printf "    Path to done file to be used by taskmage\n    (recommended: ~/Documents/todo/done.txt)\n"
    echo

    # :environment_variable.usage
    printf "  %s\n" "TASKMAGE_DELETEDFILE (required)"
    printf "    Path to deleted file to be used by taskmage\n    (recommended: ~/Documents/todo/deleted.txt)\n"
    echo

  fi
}

# :command.usage
tm_add_usage() {
  printf "tm add - Add a task\n\n"
  printf "Alias: a\n"
  echo

  printf "%s\n" "Usage:"
  printf "  tm add TASK...\n"
  printf "  tm add --help | -h\n"
  echo

  # :command.long_usage
  if [[ -n "$long_usage" ]]; then
    printf "%s\n" "Options:"

    # :command.usage_fixed_flags
    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo

    # :command.usage_args
    printf "%s\n" "Arguments:"

    # :argument.usage
    printf "  %s\n" "TASK..."
    printf "\n"
    echo

    # :command.usage_examples
    printf "%s\n" "Examples:"
    printf "  tm add take the bins out\n"
    printf "  tm add buy a loaf of bread +groceries\n"
    printf "  tm add call dad @phone\n"
    echo

  fi
}

# :command.usage
tm_list_usage() {
  printf "tm list - List tasks\n\n"
  printf "Alias: ls, l\n"
  echo

  printf "%s\n" "Usage:"
  printf "  tm [list] [TASK_LIST]\n"
  printf "  tm list --help | -h\n"
  echo

  # :command.long_usage
  if [[ -n "$long_usage" ]]; then
    printf "%s\n" "Options:"

    # :command.usage_fixed_flags
    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo

    # :command.usage_args
    printf "%s\n" "Arguments:"

    # :argument.usage
    printf "  %s\n" "TASK_LIST"
    printf "\n"
    printf "    %s\n" "Allowed: all, a, archived, x, complete, c, deleted, del, removed, rm, pending, p, done, d"
    echo

    # :command.usage_examples
    printf "%s\n" "Examples:"
    printf "  tm list\n"
    printf "  tm list pending\n"
    printf "  tm list deleted\n"
    printf "  tm list all\n"
    echo

  fi
}

# :command.usage
tm_done_usage() {
  printf "tm done - Mark a task as completed\n\n"
  printf "Alias: d, finish, f\n"
  echo

  printf "%s\n" "Usage:"
  printf "  tm done TASK_ID\n"
  printf "  tm done --help | -h\n"
  echo

  # :command.long_usage
  if [[ -n "$long_usage" ]]; then
    printf "%s\n" "Options:"

    # :command.usage_fixed_flags
    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo

    # :command.usage_args
    printf "%s\n" "Arguments:"

    # :argument.usage
    printf "  %s\n" "TASK_ID"
    printf "\n"
    echo

    # :command.usage_examples
    printf "%s\n" "Examples:"
    printf "  tm done 1\n"
    echo

  fi
}

# :command.usage
tm_delete_usage() {
  printf "tm delete - Delete a task - move to deleted file\n\n"
  printf "Alias: del, remove, rm\n"
  echo

  printf "%s\n" "Usage:"
  printf "  tm delete TASK_ID\n"
  printf "  tm delete --help | -h\n"
  echo

  # :command.long_usage
  if [[ -n "$long_usage" ]]; then
    printf "%s\n" "Options:"

    # :command.usage_fixed_flags
    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo

    # :command.usage_args
    printf "%s\n" "Arguments:"

    # :argument.usage
    printf "  %s\n" "TASK_ID"
    printf "\n"
    echo

    # :command.usage_examples
    printf "%s\n" "Examples:"
    printf "  tm delete 1\n"
    echo

  fi
}

# :command.usage
tm_purge_usage() {
  printf "tm purge - Purge a task - remove from deleted file\n\n"
  printf "Alias: p\n"
  echo

  printf "%s\n" "Usage:"
  printf "  tm purge TASK_ID\n"
  printf "  tm purge --help | -h\n"
  echo

  # :command.long_usage
  if [[ -n "$long_usage" ]]; then
    printf "%s\n" "Options:"

    # :command.usage_fixed_flags
    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo

    # :command.usage_args
    printf "%s\n" "Arguments:"

    # :argument.usage
    printf "  %s\n" "TASK_ID"
    printf "\n"
    echo

    # :command.usage_examples
    printf "%s\n" "Examples:"
    printf "  tm purge 1\n"
    echo

  fi
}

# :command.usage
tm_archive_usage() {
  printf "tm archive - Archive completed tasks - move from todo file to done file\n\n"
  printf "Alias: x\n"
  echo

  printf "%s\n" "Usage:"
  printf "  tm archive\n"
  printf "  tm archive --help | -h\n"
  echo

  # :command.long_usage
  if [[ -n "$long_usage" ]]; then
    printf "%s\n" "Options:"

    # :command.usage_fixed_flags
    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo

    # :command.usage_examples
    printf "%s\n" "Examples:"
    printf "  tm archive\n"
    echo

  fi
}

# :command.normalize_input
# :command.normalize_input_function
normalize_input() {
  local arg passthru flags
  passthru=false

  while [[ $# -gt 0 ]]; do
    arg="$1"
    if [[ $passthru == true ]]; then
      input+=("$arg")
    elif [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
      input+=("${BASH_REMATCH[1]}")
      input+=("${BASH_REMATCH[2]}")
    elif [[ $arg =~ ^(-[a-zA-Z0-9])=(.+)$ ]]; then
      input+=("${BASH_REMATCH[1]}")
      input+=("${BASH_REMATCH[2]}")
    elif [[ $arg =~ ^-([a-zA-Z0-9][a-zA-Z0-9]+)$ ]]; then
      flags="${BASH_REMATCH[1]}"
      for ((i = 0; i < ${#flags}; i++)); do
        input+=("-${flags:i:1}")
      done
    elif [[ "$arg" == "--" ]]; then
      passthru=true
      input+=("$arg")
    else
      input+=("$arg")
    fi

    shift
  done
}

# :command.inspect_args
inspect_args() {
  if ((${#args[@]})); then
    readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
    echo args:
    for k in "${sorted_keys[@]}"; do
      echo "- \${args[$k]} = ${args[$k]}"
    done
  else
    echo args: none
  fi

  if ((${#deps[@]})); then
    readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
    echo
    echo deps:
    for k in "${sorted_keys[@]}"; do
      echo "- \${deps[$k]} = ${deps[$k]}"
    done
  fi

  if ((${#env_var_names[@]})); then
    readarray -t sorted_names < <(printf '%s\n' "${env_var_names[@]}" | sort)
    echo
    echo "environment variables:"
    for k in "${sorted_names[@]}"; do
      echo "- \$$k = ${!k:-}"
    done
  fi
}

# :command.user_lib
# src/lib/find_tags.sh
find_tags() {
    # $1 is the task
    # $2 can be @ or +
    local prefix="$2"
    grep -oP "[$prefix]\w+" <<<"$1" | grep -v "^[$prefix]x$" | tr '\n' ' '
}

# src/lib/sort_file.sh
sort_file() {
    sort -ud $TASKMAGE_TODOFILE | awk '/^\(/ {print; next} {lines[++n]=$0} END {for(i=1; i<=n; i++) print lines[i]}' >/tmp/$TASKMAGE_TODOFILE
    mv /tmp/$TASKMAGE_TODOFILE $TASKMAGE_TODOFILE
}

# :command.command_functions
# :command.function
tm_add_command() {

  # src/add_command.sh
  local description="$(sed -E 's/\bpri:[A-Z]\b//g; s/@[A-Za-z0-9_]+\b//g; s/\+[A-Za-z0-9_]+\b//g; s/[[:space:]]+/ /g; s/^ //; s/ $//' <<<"${args[task]}")"
  local pri="$(grep -oP 'pri:\K[A-Z]' <<<"${args[task]}")"
  [ -n "$pri" ] && pri="($pri) "
  local context="$(find_tags "${args[task]}" @)"
  local project="$(find_tags "${args[task]}" +)"
  local date="$(date +%F)"

  local task="$pri$date $description $project $context"
  echo "$task" >>$TASKMAGE_TODOFILE # write task to file
  sort_file
  local line="$(grep -n "$task" $TASKMAGE_TODOFILE)"
  echo "Added task ${line%%:*} '$description'."
  sed -E -i 's/[ \t]+$//' $TASKMAGE_TODOFILE # remove trailing whitespace

}

# :command.function
tm_list_command() {

  # src/list_command.sh
  # shellcheck disable=SC2148
  # shellcheck disable=SC2168
  # shellcheck disable=SC2154
  if [[ "${args[task_list]}" == 'archived' ]] || [[ "${args[task_list]}" == 'x' ]]; then
      local DATAFILE="$TASKMAGE_DONEFILE"
  elif [[ "${args[task_list]}" == 'deleted' ]] || [[ "${args[task_list]}" == 'del' ]] || [[ "${args[task_list]}" == 'removed' ]] || [[ "${args[task_list]}" == 'rm' ]]; then
      local DATAFILE="$TASKMAGE_DELETEDFILE"
  elif [[ "${args[task_list]}" == 'all' ]] || [[ "${args[task_list]}" == 'all' ]]; then
      # TODO: add metadata specifying the origin of the file for each task
      cat "$TASKMAGE_TODOFILE" >/tmp/taskmage-all.txt
      cat "$TASKMAGE_DONEFILE" >>/tmp/taskmage-all.txt
      cat "$TASKMAGE_DELETEDFILE" >>/tmp/taskmage-all.txt
      local DATAFILE='/tmp/taskmage-all.txt'
  elif [[ "${args[task_list]}" == 'pending' ]] || [[ "${args[task_list]}" == 'p' ]]; then
      # TODO
      echo 'todo'
      exit 0
  elif [[ "${args[task_list]}" == 'completed' ]] || [[ "${args[task_list]}" == 'c' ]]; then
      # TODO
      echo 'todo'
      exit 0
  else
      local DATAFILE="$TASKMAGE_TODOFILE"
  fi

  # get value of each field
  local number_of_tasks="$(wc -l $DATAFILE)"
  for ((i = 1; i <= "${number_of_tasks%% *}"; i++)); do
      local id=$i
      local task="$(sed -n "${i}p" $DATAFILE)"
      if [[ "$task" = x* ]]; then
          local completion_status='Complete'
      else
          local completion_status='Pending'
      fi
      local description="$(sed -E 's/^x //; s/^\([A-Z]\) //; s/^[0-9-]+ //; s/^[0-9-]+ //; s/ [+@][^ ]*//g; s/due:\S+//g; s/^[[:space:]]*//; s/[[:space:]]*$//' <<<"$task")"
      local pri="$(grep -oP '^\([A-Z]\)' <<<"$task" | sed 's/[()]//g')"
      local context="$(find_tags "$task" @)"
      local project="$(find_tags "$task" +)"
      local due_date="$(grep -oP 'due:\K[0-9]{4}-[0-9]{2}-[0-9]{2}' <<<"$task")"

      # find the completion and creation dates
      # this does a regex which matches only when the date is preceded by an x, a (letter) or another date
      local completion_creation="$(grep -oP '^x\s+(?:\([A-Z]\)\s+)?\d{4}-\d{2}-\d{2}(?:\s+\d{4}-\d{2}-\d{2})?|^(?:\([A-Z]\)\s+)\d{4}-\d{2}-\d{2}(?:\s+\d{4}-\d{2}-\d{2})?|^\d{4}-\d{2}-\d{2}(?=\s)' <<<"$task" | grep -oP '\d{4}-\d{2}-\d{2}')"

      # LOGIC:
      # if it has two dates, then consider the first date to be completion date and the second date to be creation
      # date
      # if it is pending and has one date, then consider that to be creation date
      # if it is complete and has one date, then consider that to be completion date
      local num_dates="$(wc -l <<<"$completion_creation")"
      if [[ "$num_dates" -eq 1 ]]; then
          [[ "$completion_status" == 'Pending' ]] && local creation_date="$completion_creation"
          [[ "$completion_status" == 'Complete' ]] && local completion_date="$completion_creation"
      elif [[ "$num_dates" -eq 2 ]]; then
          local completion_date="$(head -1 <<<"$completion_creation")"
          local creation_date="$(tail -1 <<<"$completion_creation")"
      fi

      local full_task+="$id\t$completion_status\t$pri\t$due_date\t$completion_date\t$creation_date\t$description\t$project\t$context\n"

      # this has to be unset before the next loop to prevent a bug where the next task has the same completion date as
      # the previous task if the next task only has one date
      unset completion_date
  done

  # print fields under respective headings
  local n="$(tput sgr0)" # no formatting
  local u="$(tput smul)" # underlined
  local headings="${u}ID${n}\t${u}Status${n}\t${u}Priority${n}\t${u}Due${n}\t${u}Completed${n}\t${u}Created${n}\t${u}Description${n}\t${u}Projects${n}\t${u}Contexts${n}\t${u}${n}"
  echo -e "$headings\n$full_task" | column -t -s $'\t'

  rm -f '/tmp/taskmage-all.txt'

}

# :command.function
tm_done_command() {

  # src/done_command.sh
  # shellcheck disable=SC2148
  # shellcheck disable=SC2168
  # shellcheck disable=SC2154
  local task="$(sed -n "${args[task_id]}p" $TASKMAGE_TODOFILE)"
  [[ "$task" = x* ]] && echo 'taskmage: error: task already completed' && exit 1
  local description="$(sed -E 's/^x //; s/^\([A-Z]\) //; s/^[0-9-]+ //; s/^[0-9-]+ //; s/ [+@].*//' <<<"$task")"

  local completion_date="$(date +%F)"
  local completed_task="$(sed "s/^(\([A-Z]\))\(.*\)/x (\1) $completion_date\2/; t; s/^/x $completion_date /" <<<"$task")"

  sed -i "${1}s/$task/$completed_task/" $TASKMAGE_TODOFILE
  echo "Completed task ${args[task_id]} '$description'."

  sort_file

}

# :command.function
tm_delete_command() {

  # src/delete_command.sh
  # shellcheck disable=SC2148
  # shellcheck disable=SC2168
  # shellcheck disable=SC2154
  local task="$(sed -n "${args[task_id]}p" $TASKMAGE_TODOFILE)"
  local description="$(sed -E 's/^x //; s/^\([A-Z]\) //; s/^[0-9-]+ //; s/^[0-9-]+ //; s/ [+@].*//' <<<"$task")"
  echo "$task" >>$TASKMAGE_DELETEDFILE
  sed -i "${args[task_id]}d" $TASKMAGE_TODOFILE
  echo "Deleted task ${args[task_id]} '$description'."

}

# :command.function
tm_purge_command() {

  # src/purge_command.sh
  # shellcheck disable=SC2148
  # shellcheck disable=SC2168
  # shellcheck disable=SC2154
  local task="$(sed -n "${args[task_id]}p" $TASKMAGE_DELETEDFILE)"
  local description="$(sed -E 's/^x //; s/^\([A-Z]\) //; s/^[0-9-]+ //; s/^[0-9-]+ //; s/ [+@].*//' <<<"$task")"
  sed -i "${args[task_id]}d" $TASKMAGE_DELETEDFILE
  echo "Purged task $1 '$description'."

}

# :command.function
tm_archive_command() {

  # src/archive_command.sh
  # shellcheck disable=SC2148
  # shellcheck disable=SC2168
  # shellcheck disable=SC2154
  grep '^x ' $TASKMAGE_TODOFILE >>$TASKMAGE_DONEFILE && sed -i '/^x /d' $TASKMAGE_TODOFILE

}

# :command.parse_requirements
parse_requirements() {
  # :command.fixed_flags_filter
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --version | -v)
        version_command
        exit
        ;;

      --help | -h)
        long_usage=yes
        tm_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  # :command.environment_variables_filter

  env_var_names+=("TASKMAGE_TODOFILE")
  env_var_names+=("TASKMAGE_DONEFILE")
  env_var_names+=("TASKMAGE_DELETEDFILE")
  if [[ -z "${TASKMAGE_TODOFILE:-}" ]]; then
    printf "missing required environment variable: TASKMAGE_TODOFILE\n" >&2
    exit 1
  fi
  if [[ -z "${TASKMAGE_DONEFILE:-}" ]]; then
    printf "missing required environment variable: TASKMAGE_DONEFILE\n" >&2
    exit 1
  fi
  if [[ -z "${TASKMAGE_DELETEDFILE:-}" ]]; then
    printf "missing required environment variable: TASKMAGE_DELETEDFILE\n" >&2
    exit 1
  fi

  # :command.dependencies_filter
  missing_deps=
  # :dependency.filter
  if ! command -v cat >/dev/null 2>&1; then
    printf "missing dependency: cat\n" >&2
    printf "%s\n\n" "taskmage depends on the GNU coreutils" >&2
    missing_deps=1
  else
    deps['cat']="$(command -v cat | head -n1)"
  fi

  # :dependency.filter
  if ! command -v sed >/dev/null 2>&1; then
    printf "missing dependency: sed\n" >&2
    printf "%s\n\n" "taskmage depends on the GNU coreutils" >&2
    missing_deps=1
  else
    deps['sed']="$(command -v sed | head -n1)"
  fi

  # :dependency.filter
  if ! command -v grep >/dev/null 2>&1; then
    printf "missing dependency: grep\n" >&2
    printf "%s\n\n" "taskmage depends on the GNU coreutils" >&2
    missing_deps=1
  else
    deps['grep']="$(command -v grep | head -n1)"
  fi

  # :dependency.filter
  if ! command -v date >/dev/null 2>&1; then
    printf "missing dependency: date\n" >&2
    printf "%s\n\n" "taskmage depends on the GNU coreutils" >&2
    missing_deps=1
  else
    deps['date']="$(command -v date | head -n1)"
  fi

  # :dependency.filter
  if ! command -v echo >/dev/null 2>&1; then
    printf "missing dependency: echo\n" >&2
    printf "%s\n\n" "taskmage depends on the GNU coreutils" >&2
    missing_deps=1
  else
    deps['echo']="$(command -v echo | head -n1)"
  fi

  # :dependency.filter
  if ! command -v wc >/dev/null 2>&1; then
    printf "missing dependency: wc\n" >&2
    printf "%s\n\n" "taskmage depends on the GNU coreutils" >&2
    missing_deps=1
  else
    deps['wc']="$(command -v wc | head -n1)"
  fi

  # :dependency.filter
  if ! command -v tput >/dev/null 2>&1; then
    printf "missing dependency: tput\n" >&2
    printf "%s\n\n" "taskmage depends on ncurses" >&2
    missing_deps=1
  else
    deps['tput']="$(command -v tput | head -n1)"
  fi

  # :dependency.filter
  if ! command -v column >/dev/null 2>&1; then
    printf "missing dependency: column\n" >&2
    printf "%s\n\n" "taskmage depends on util-linux" >&2
    missing_deps=1
  else
    deps['column']="$(command -v column | head -n1)"
  fi

  if [[ -n $missing_deps ]]; then
    exit 1
  fi

  # :command.command_filter
  action=${1:-}

  case $action in

    add | a)
      action="add"
      shift
      tm_add_parse_requirements "$@"
      shift $#
      ;;

    list | ls | l)
      action="list"
      shift
      tm_list_parse_requirements "$@"
      shift $#
      ;;

    done | d | finish | f)
      action="done"
      shift
      tm_done_parse_requirements "$@"
      shift $#
      ;;

    delete | del | remove | rm)
      action="delete"
      shift
      tm_delete_parse_requirements "$@"
      shift $#
      ;;

    purge | p)
      action="purge"
      shift
      tm_purge_parse_requirements "$@"
      shift $#
      ;;

    archive | x)
      action="archive"
      shift
      tm_archive_parse_requirements "$@"
      shift $#
      ;;

    # :command.command_fallback
    *)
      action="list"
      tm_list_parse_requirements "$@"
      shift $#
      ;;

  esac

  # :command.parse_requirements_while
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)
        # :command.parse_requirements_case
        # :command.parse_requirements_case_simple
        printf "invalid argument: %s\n" "$key" >&2
        exit 1

        ;;

    esac
  done

}

# :command.parse_requirements
tm_add_parse_requirements() {
  # :command.fixed_flags_filter
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        tm_add_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  # :command.command_filter
  action="add"

  # :command.parse_requirements_while
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)
        # :command.parse_requirements_case
        # :command.parse_requirements_case_repeatable
        # :argument.case_repeatable
        escaped="$(printf '%q' "$1")"
        if [[ -z ${args['task']+x} ]]; then
          args['task']="$escaped"
        else
          args['task']="${args['task']} $escaped"

        fi
        shift

        ;;

    esac
  done

  # :command.required_args_filter
  if [[ -z ${args['task']+x} ]]; then
    printf "missing required argument: TASK\nusage: tm add TASK...\n" >&2

    exit 1
  fi

}

# :command.parse_requirements
tm_list_parse_requirements() {
  # :command.fixed_flags_filter
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        tm_list_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  # :command.command_filter
  action="list"

  # :command.parse_requirements_while
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)
        # :command.parse_requirements_case
        # :command.parse_requirements_case_simple
        # :argument.case
        if [[ -z ${args['task_list']+x} ]]; then
          args['task_list']=$1
          shift
        else
          printf "invalid argument: %s\n" "$key" >&2
          exit 1
        fi

        ;;

    esac
  done

  # :command.whitelist_filter
  if [[ -n ${args['task_list']:-} ]] && [[ ! ${args['task_list']:-} =~ ^(all|a|archived|x|complete|c|deleted|del|removed|rm|pending|p|done|d)$ ]]; then
    printf "%s\n" "task_list must be one of: all, a, archived, x, complete, c, deleted, del, removed, rm, pending, p, done, d" >&2
    exit 1
  fi

}

# :command.parse_requirements
tm_done_parse_requirements() {
  # :command.fixed_flags_filter
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        tm_done_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  # :command.command_filter
  action="done"

  # :command.parse_requirements_while
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)
        # :command.parse_requirements_case
        # :command.parse_requirements_case_simple
        # :argument.case
        if [[ -z ${args['task_id']+x} ]]; then
          args['task_id']=$1
          shift
        else
          printf "invalid argument: %s\n" "$key" >&2
          exit 1
        fi

        ;;

    esac
  done

  # :command.required_args_filter
  if [[ -z ${args['task_id']+x} ]]; then
    printf "missing required argument: TASK_ID\nusage: tm done TASK_ID\n" >&2

    exit 1
  fi

}

# :command.parse_requirements
tm_delete_parse_requirements() {
  # :command.fixed_flags_filter
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        tm_delete_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  # :command.command_filter
  action="delete"

  # :command.parse_requirements_while
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)
        # :command.parse_requirements_case
        # :command.parse_requirements_case_simple
        # :argument.case
        if [[ -z ${args['task_id']+x} ]]; then
          args['task_id']=$1
          shift
        else
          printf "invalid argument: %s\n" "$key" >&2
          exit 1
        fi

        ;;

    esac
  done

  # :command.required_args_filter
  if [[ -z ${args['task_id']+x} ]]; then
    printf "missing required argument: TASK_ID\nusage: tm delete TASK_ID\n" >&2

    exit 1
  fi

}

# :command.parse_requirements
tm_purge_parse_requirements() {
  # :command.fixed_flags_filter
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        tm_purge_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  # :command.command_filter
  action="purge"

  # :command.parse_requirements_while
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)
        # :command.parse_requirements_case
        # :command.parse_requirements_case_simple
        # :argument.case
        if [[ -z ${args['task_id']+x} ]]; then
          args['task_id']=$1
          shift
        else
          printf "invalid argument: %s\n" "$key" >&2
          exit 1
        fi

        ;;

    esac
  done

  # :command.required_args_filter
  if [[ -z ${args['task_id']+x} ]]; then
    printf "missing required argument: TASK_ID\nusage: tm purge TASK_ID\n" >&2

    exit 1
  fi

}

# :command.parse_requirements
tm_archive_parse_requirements() {
  # :command.fixed_flags_filter
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        tm_archive_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  # :command.command_filter
  action="archive"

  # :command.parse_requirements_while
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)
        # :command.parse_requirements_case
        # :command.parse_requirements_case_simple
        printf "invalid argument: %s\n" "$key" >&2
        exit 1

        ;;

    esac
  done

}

# :command.initialize
initialize() {
  declare -g version="0.1.0"
  set -e

}

# :command.run
run() {
  # :command.globals
  declare -g long_usage=''
  declare -g -A args=()
  declare -g -A deps=()
  declare -g -a env_var_names=()
  declare -g -a input=()

  normalize_input "$@"
  parse_requirements "${input[@]}"

  case "$action" in
    "add") tm_add_command ;;
    "list") tm_list_command ;;
    "done") tm_done_command ;;
    "delete") tm_delete_command ;;
    "purge") tm_purge_command ;;
    "archive") tm_archive_command ;;
  esac
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  initialize
  run "$@"
fi
